export const allimg = [
  { id: 1, img: "/img/ane.jpg", stat: "" },
  { id: 1, img: "/img/ane.jpg", stat: "" },
  { id: 2, img: "/img/bulbizarre.jpg", stat: "" },
  { id: 2, img: "/img/bulbizarre.jpg", stat: "" },
  { id: 3, img: "/img/cochon.jpg", stat: "" },
  { id: 3, img: "/img/cochon.jpg", stat: "" },
  { id: 4, img: "/img/donkekong.jpg", stat: "" },
  { id: 4, img: "/img/donkekong.jpg", stat: "" },
  { id: 5, img: "/img/girafe.jpg", stat: "" },
  { id: 5, img: "/img/girafe.jpg", stat: "" },
  { id: 6, img: "/img/hibou.jpg", stat: "" },
  { id: 6, img: "/img/hibou.jpg", stat: "" },
  { id: 7, img: "/img/link.jpg", stat: "" },
  { id: 7, img: "/img/link.jpg", stat: "" },
  { id: 8, img: "/img/nounours.jpg", stat: "" },
  { id: 8, img: "/img/nounours.jpg", stat: "" },
  { id: 9, img: "/img/nounours1.jpg", stat: "" },
  { id: 9, img: "/img/nounours1.jpg", stat: "" },
  { id: 10, img: "/img/nounours2.jpg", stat: "" },
  { id: 10, img: "/img/nounours2.jpg", stat: "" },
  { id: 11, img: "/img/panda.jpg", stat: "" },
  { id: 11, img: "/img/panda.jpg", stat: "" },
  { id: 12, img: "/img/pikachu.jpg", stat: "" },
  { id: 12, img: "/img/pikachu.jpg", stat: "" },
  { id: 13, img: "/img/poule.jpg", stat: "" },
  { id: 13, img: "/img/poule.jpg", stat: "" },
  { id: 14, img: "/img/renard.jpg", stat: "" },
  { id: 14, img: "/img/renard.jpg", stat: "" },
  { id: 15, img: "/img/riolu.jpg", stat: "" },
  { id: 15, img: "/img/riolu.jpg", stat: "" },
  { id: 16, img: "/img/salameche.jpg", stat: "" },
  { id: 16, img: "/img/salameche.jpg", stat: "" },

];